### ISSUE TITLE
bower로 tui.chart 설치시 오류 메시지

### ISSUE THREAD

**Issue by Drdoteam** [nhnent/tui.chart#5]
안녕하세요.
클라우드플랫폼개발팀 신진호 입니다.

high chart 라이선스 만료로 tui.chart를 적용하려 합니다.

Wiki 내용대로 bower를 사용해서 tui.chart를 설치시 오류 메시지가 출력됩니다.
가이드 부탁드립니다.
```
$ bower install tui-chart
bower tui-chart#*           not-cached https://github.com/nhnent/tui.chart.git#*
bower tui-chart#*              resolve https://github.com/nhnent/tui.chart.git#*
bower tui-chart#*             download https://github.com/nhnent/tui.chart/archive/2.5.0.tar.gz
bower tui-chart#*              extract archive.tar.gz
bower tui-chart#*             resolved https://github.com/nhnent/tui.chart.git#2.5.0
bower raphael#v2.1.4b       not-cached https://github.com/nhnent/raphael.git#v2.1.4b
bower raphael#v2.1.4b          resolve https://github.com/nhnent/raphael.git#v2.1.4b
bower tui-code-snippet#1.0.8       not-cached https://github.com/nhnent/tui.code-snippet.git#1.0.8
bower tui-code-snippet#1.0.8          resolve https://github.com/nhnent/tui.code-snippet.git#1.0.8
bower tui-component-effects#~1.1.0 not-cached https://github.com/nhnent/tui.component.effects.git#~1.1.0
bower tui-component-effects#~1.1.0    resolve https://github.com/nhnent/tui.component.effects.git#~1.1.0
bower raphael#v2.1.4b                download https://github.com/nhnent/raphael/archive/v2.1.4b.tar.gz
bower tui-code-snippet#1.0.8         download https://github.com/nhnent/tui.code-snippet/archive/1.0.8.tar.gz
bower tui-component-effects#~1.1.0   download https://github.com/nhnent/tui.component.effects/archive/1.1.1.tar.gz
bower tui-component-effects#~1.1.0    extract archive.tar.gz
bower tui-component-effects#~1.1.0   resolved https://github.com/nhnent/tui.component.effects.git#1.1.1
bower tui-code-snippet#~1.1.0      not-cached https://github.com/nhnent/tui.code-snippet.git#~1.1.0
bower tui-code-snippet#~1.1.0         resolve https://github.com/nhnent/tui.code-snippet.git#~1.1.0
bower tui-code-snippet#~1.1.0        download https://github.com/nhnent/tui.code-snippet/archive/1.1.3.tar.gz
bower raphael#v2.1.4b                 extract archive.tar.gz
bower raphael#v2.1.4b                resolved https://github.com/nhnent/raphael.git#v2.1.4b
bower tui-code-snippet#1.0.8          extract archive.tar.gz
bower tui-code-snippet#1.0.8         resolved https://github.com/nhnent/tui.code-snippet.git#1.0.8
bower tui-code-snippet#~1.1.0         extract archive.tar.gz
bower tui-code-snippet#~1.1.0        resolved https://github.com/nhnent/tui.code-snippet.git#1.1.3
bower                               ECONFLICT Unable to find suitable version for tui-code-snippet
```

**Comment by junghwan-park** [comment]
안녕하세요 FE개발랩 박정환입니다.

사용하고 계신 개발 환경과 bower 버전을 알 수 있을까요?
bower 버전은 `$ bower --version`을 통해 알 수 있습니다.

제가 사용하는 환경은 OSX/bower-1.8.0이고요, 동일한 커맨드로 설치시 다음과 같이 진행이 됩니다.

```
$ bower install tui-chart
bower tui-chart#*           not-cached https://github.com/nhnent/tui.chart.git#*
bower tui-chart#*              resolve https://github.com/nhnent/tui.chart.git#*
bower tui-chart#*             checkout 2.5.0
bower tui-chart#*             resolved https://github.com/nhnent/tui.chart.git#2.5.0
bower raphael#v2.1.4b       not-cached https://github.com/nhnent/raphael.git#v2.1.4b
bower raphael#v2.1.4b          resolve https://github.com/nhnent/raphael.git#v2.1.4b
bower tui-code-snippet#1.0.8       not-cached https://github.com/nhnent/tui.code-snippet.git#1.0.8
bower tui-code-snippet#1.0.8          resolve https://github.com/nhnent/tui.code-snippet.git#1.0.8
bower tui-component-effects#~1.1.0 not-cached https://github.com/nhnent/tui.component.effects.git#~1.1.0
bower tui-component-effects#~1.1.0    resolve https://github.com/nhnent/tui.component.effects.git#~1.1.0
bower raphael#v2.1.4b                checkout v2.1.4b
bower tui-component-effects#~1.1.0   checkout 1.1.1
bower tui-code-snippet#1.0.8         checkout 1.0.8
bower tui-component-effects#~1.1.0   resolved https://github.com/nhnent/tui.component.effects.git#1.1.1
bower tui-code-snippet#~1.1.0      not-cached https://github.com/nhnent/tui.code-snippet.git#~1.1.0
bower tui-code-snippet#~1.1.0         resolve https://github.com/nhnent/tui.code-snippet.git#~1.1.0
bower tui-code-snippet#~1.1.0        checkout 1.1.3
bower tui-code-snippet#1.0.8         resolved https://github.com/nhnent/tui.code-snippet.git#1.0.8
bower raphael#v2.1.4b                resolved https://github.com/nhnent/raphael.git#v2.1.4b
bower tui-code-snippet#~1.1.0        resolved https://github.com/nhnent/tui.code-snippet.git#1.1.3

Unable to find a suitable version for tui-code-snippet, please choose one by typing one of the numbers below:
    1) tui-code-snippet#1.0.8 which resolved to 1.0.8 and is required by tui-chart#2.5.0
    2) tui-code-snippet#~1.1.0 which resolved to 1.1.3 and is required by tui-component-effects#1.1.1

Prefix the choice with ! to persist it to bower.json

? Answer 
```

의존성 충돌이 일어난 컴포넌트의 버전의 번호를 사용자가 직접 shell에 입력해서 설치를 계속하게 됩니다.

bower의 버전이 낮다면, `$ npm install -g bower` 명령어로 bower 버전을 업그레이드를 진행하시면 됩니다.

업그레이드 후에도 tui-chart 설치에 문제가 있는지 알려주시면 감사하겠습니다.

**Comment by Drdoteam** [comment]
Windows 7, bower 1.8.0 입니다.

**Comment by Drdoteam** [comment]
verbose로 실행했을 때 결과 입니다.
```
$ bower install "tui-chart#2.5.0" --verbose
bower tui-chart#2.5.0           cached https://github.com/nhnent/tui.chart.git#2.5.0
bower tui-chart#2.5.0         validate 2.5.0 against https://github.com/nhnent/tui.chart.git#2.5.0
bower raphael#v2.1.4b           cached https://github.com/nhnent/raphael.git#v2.1.4b
bower raphael#v2.1.4b         validate v2.1.4b against https://github.com/nhnent/raphael.git#v2.1.4b
bower tui-component-effects#~1.1.0           cached https://github.com/nhnent/tui.component.effects.git#1.1.1
bower tui-component-effects#~1.1.0         validate 1.1.1 against https://github.com/nhnent/tui.component.effects.git#~1.1.0
bower tui-code-snippet#1.0.8                 cached https://github.com/nhnent/tui.code-snippet.git#1.0.8
bower tui-code-snippet#1.0.8               validate 1.0.8 against https://github.com/nhnent/tui.code-snippet.git#1.0.8
bower tui-code-snippet#~1.1.0                cached https://github.com/nhnent/tui.code-snippet.git#1.1.3
bower tui-code-snippet#~1.1.0              validate 1.1.3 against https://github.com/nhnent/tui.code-snippet.git#~1.1.0
bower                                     ECONFLICT Unable to find suitable version for tui-code-snippet

Stack trace:
tui-code-snippet: Unable to find suitable version for tui-code-snippet
    at createError (C:\Users\NHNEnt\AppData\Roaming\npm\node_modules\bower\lib\util\createError.js:4:15)
    at Manager._electSuitable (C:\Users\NHNEnt\AppData\Roaming\npm\node_modules\bower\lib\core\Manager.js:825:15)
    at C:\Users\NHNEnt\AppData\Roaming\npm\node_modules\bower\lib\core\Manager.js:609:25
From previous event:
    at Manager._dissect (C:\Users\NHNEnt\AppData\Roaming\npm\node_modules\bower\lib\core\Manager.js:618:6)

Console trace:
Error
    at StandardRenderer.error (C:\Users\NHNEnt\AppData\Roaming\npm\node_modules\bower\lib\renderers\StandardRenderer.js:81:37)
    at Logger.<anonymous> (C:\Users\NHNEnt\AppData\Roaming\npm\node_modules\bower\lib\bin\bower.js:110:26)
    at Logger.emit (events.js:107:17)
    at Logger.emit (C:\Users\NHNEnt\AppData\Roaming\npm\node_modules\bower\lib\node_modules\bower-logger\lib\Logger.js:29:39)
    at C:\Users\NHNEnt\AppData\Roaming\npm\node_modules\bower\lib\commands\index.js:48:20
    at _rejected (C:\Users\NHNEnt\AppData\Roaming\npm\node_modules\bower\lib\node_modules\q\q.js:844:24)
    at C:\Users\NHNEnt\AppData\Roaming\npm\node_modules\bower\lib\node_modules\q\q.js:870:30
    at Promise.when (C:\Users\NHNEnt\AppData\Roaming\npm\node_modules\bower\lib\node_modules\q\q.js:1122:31)
    at Promise.promise.promiseDispatch (C:\Users\NHNEnt\AppData\Roaming\npm\node_modules\bower\lib\node_modules\q\q.js:788:41)
    at C:\Users\NHNEnt\AppData\Roaming\npm\node_modules\bower\lib\node_modules\q\q.js:604:44
System info:
Bower version: 1.8.0
Node version: 0.12.0
OS: Windows_NT 6.1.7601 x64
```

**Comment by Drdoteam** [comment]
tui-code-snippet 버전을 못 찾는 것 같습니다.

**Comment by Drdoteam** [comment]
근데 저는 추가 입력이 없고.... 그냥 종료되는 걸까요...

**Comment by junghwan-park** [comment]
추가 선택없이 종료되는 정확한 원인은 모르겠으나,
tui-code-snippet버전은 찾았으나 올바른 버전을 고르지 못해 에러가 발생되고 종료되는것으로 보입니다.

https://bower.io/docs/api/#install 링크를 보시면 `bower install` 커맨드의 option에 `-F`옵션이 있는데요, 의존성 충돌시 최신 버전을 따르게끔 하는 옵션입니다.
`-F`옵션을 넣어서 설치도 해보셨나요~?

**Comment by Drdoteam** [comment]
되는 것 같네요.
감사합니다.
```
$ bower install "tui-chart#2.5.0" --verbose -F
bower tui-chart#2.5.0           cached https://github.com/nhnent/tui.chart.git#2.5.0
bower tui-chart#2.5.0         validate 2.5.0 against https://github.com/nhnent/tui.chart.git#2.5.0
bower raphael#v2.1.4b           cached https://github.com/nhnent/raphael.git#v2.1.4b
bower raphael#v2.1.4b         validate v2.1.4b against https://github.com/nhnent/raphael.git#v2.1.4b
bower tui-component-effects#~1.1.0           cached https://github.com/nhnent/tui.component.effects.git#1.1.1
bower tui-component-effects#~1.1.0         validate 1.1.1 against https://github.com/nhnent/tui.component.effects.git#~1.1.0
bower tui-code-snippet#~1.1.0                cached https://github.com/nhnent/tui.code-snippet.git#1.1.3
bower tui-code-snippet#~1.1.0              validate 1.1.3 against https://github.com/nhnent/tui.code-snippet.git#~1.1.0

Please note that,
    res, tui-chart#2.5.0 depends on tui-code-snippet#1.0.8 which resolved to tui-code-snippet#1.0.8
    tui-component-effects#1.1.1 depends on tui-code-snippet#~1.1.0 which resolved to tui-code-snippet#1.1.3
Resort to using tui-code-snippet# which resolved to tui-code-snippet#1.1.3
Code incompatibilities may occur.

bower tui-code-snippet                   resolution Saved tui-code-snippet#~1.1.0 as resolution
bower tui-code-snippet#~1.1.0               install tui-code-snippet#1.1.3
bower tui-chart#2.5.0                       install tui-chart#2.5.0
bower tui-component-effects#~1.1.0          install tui-component-effects#1.1.1
bower raphael#v2.1.4b                       install raphael#v2.1.4b
bower                                       no-json No bower.json file to save to, use bower init to create one

tui-code-snippet#1.1.3 bower_components\tui-code-snippet

tui-chart#2.5.0 bower_components\tui-chart
├── raphael#v2.1.4b
├── tui-code-snippet#1.1.3
└── tui-component-effects#1.1.1

tui-component-effects#1.1.1 bower_components\tui-component-effects
└── tui-code-snippet#1.1.3

raphael#v2.1.4b bower_components\raphael
```

**Comment by Drdoteam** [comment]
@junghwan-park 그리고 Wiki > getting started > include files에 
tui component effect 경로가 잘 못 된 것 같습니다.
아래와 같이 dist 디렉터리 밑에 js 파일이 있었습니다.
```
<script src="bower_components/tui-component-effects/dist/tui-component-effects.min.js"></script>
```

**Comment by junghwan-park** [comment]
@Drdoteam 문서에 변경된 경로가 반영되지 않았네요. 
경로를 수정해서 문서에 반영 후, 해당 이슈는 종료처리 하겠습니다.  

감사합니다. :)
